// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe0XeegiF6iABVS2KMyU2q733R8aVnB6k',
    appId: '1:302510788231:web:6bb2f62aa13c4f26adb222',
    messagingSenderId: '302510788231',
    projectId: 'easy-task-9beec',
    authDomain: 'easy-task-9beec.firebaseapp.com',
    storageBucket: 'easy-task-9beec.appspot.com',
    measurementId: 'G-6HS5Q5BQQ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1z_rHqvg_poqsA8IVDgpEcgSJcInJiLM',
    appId: '1:302510788231:android:8b33a20481d664f5adb222',
    messagingSenderId: '302510788231',
    projectId: 'easy-task-9beec',
    storageBucket: 'easy-task-9beec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-tYrunyg-3prNhCgVUIhS9DJ8QxIae5Y',
    appId: '1:302510788231:ios:a4e7cbb67f0ba6afadb222',
    messagingSenderId: '302510788231',
    projectId: 'easy-task-9beec',
    storageBucket: 'easy-task-9beec.appspot.com',
    iosClientId: '302510788231-na9f9am93qmh77njlp9ooo56vu77s2g4.apps.googleusercontent.com',
    iosBundleId: 'com.example.easyTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-tYrunyg-3prNhCgVUIhS9DJ8QxIae5Y',
    appId: '1:302510788231:ios:a4e7cbb67f0ba6afadb222',
    messagingSenderId: '302510788231',
    projectId: 'easy-task-9beec',
    storageBucket: 'easy-task-9beec.appspot.com',
    iosClientId: '302510788231-na9f9am93qmh77njlp9ooo56vu77s2g4.apps.googleusercontent.com',
    iosBundleId: 'com.example.easyTask',
  );
}
